### ISSUE TITLE
NL voice not available

### ISSUE THREAD

**Issue by cwortel** [narakeet/examples#2]
Gojko I think you forgot to commit your changes :) Trying dutch, but can't find it yet.

**Comment by gojko** [comment]
need to publish the new version, will do it over the weekend

**Comment by cwortel** [comment]
Cool, thanks ;)

**Comment by gojko** [comment]
sorry for not replying to this for so long, had to take a break from videopuppet for a while. you can use NL voice with Maartje

**Comment by cwortel** [comment]
cheers, works like a charm

 :)

**Comment by gojko** [comment]
does it sound ok or robotic?

**Comment by cwortel** [comment]
A bit robotic and tempo is a bit fast in default, but it’s not bad. I’ll have to tweak the texts a bit to find out what works best.


Met vriendelijke groeten/Kind regards,
 
Cirilo Wortel
Owner and Principal Consultant at Greenlight it
 
Email: cirilo@greenlight-it.nl
Tel: +31 (0)6 4808 0548
 
Padangstraat 66
3531 TD Utrecht
The Netherlands
http://greenlight-it.nl
  
Member of the Federation of Agile Testers: http://fat-nl.org/ <http://fat-nl.org/>

**Comment by gojko** [comment]
ok, i'll see if I can add some tempo controls as well
