### ISSUE TITLE
API or local library

### ISSUE THREAD

**Issue by michael-fawzy** [narakeet/examples#4]
Hello,
Do you have an API or a local library to create multiple videos at once locally instead of having to wait each time to upload files and wait for the rendering to finish then download the video.
I know you have Github action, but I need something to use local files on my pc, not files on Github

**Comment by gojko** [comment]
Hi, there's no batch feature in the api, but you could run things in parallel so you don't have to wait.

**Comment by gojko** [comment]
Hi @michael-fawzy - we just released an improved API + command line client that would let you use local files on your PC. Check out https://www.narakeet.com/news/2021/03/22/improved-api.html for more info and an example
